#!/bin/bash -e

usage="$0 lb_name"

if [[ $# -ne 1 ]]; then
  echo 'ERROR: Invalid usage'
  echo $usage
  exit 1
fi

lb_name=$1

set -x
aws elb add-tags --load-balancer-names $lb_name --tags "$(cat /tmp/tags-${lb_name}.json)"
set +x
