#!/bin/bash

aws ec2 describe-instances | jq -rc '.Reservations[].Instances[] | [.Placement.AvailabilityZone, .InstanceId, .State.Name, (.PublicIpAddress | if .==null then "Private" else "Public" end), (.Tags[] | select(.Key=="Name") | .Value)] | @csv'
