#!/bin/bash
key=${1:-access_logs.s3.bucket}

cat - | while read lb_arn; do
  if [[ $key == 'all' ]]; then
    aws elbv2 describe-load-balancer-attributes --load-balancer-arn "$lb_arn" | jq -c
  else
    aws elbv2 describe-load-balancer-attributes --load-balancer-arn "$lb_arn" | jq -c \
    --arg lb_arn "$lb_arn" --arg key "$key" '.Attributes[] | select(.Key==$key) | {arn: $lb_arn, key: $key, value: .Value}'
  fi
done
