#!/bin/bash

aws ec2 describe-instances | jq -rc '.Reservations[].Instances[] | [.Placement.AvailabilityZone, .InstanceId, (.Tags[] | select(.Key=="Name") | .Value)] | @csv' | TABLE_ADD_HEADER=0 csv2table 
