#!/bin/bash -e

lbs=$*

if [[ -z "$lbs" ]]; then
  lbs=$(aws elb describe-load-balancers | jq  -r '.LoadBalancerDescriptions[].LoadBalancerName')
  if [[ -z "$lbs" ]]; then
    echo "STATUS: Did not find any load balancers" >&2
    exit 1
  fi
fi

for lb in $lbs; do
  output=$(aws elb describe-load-balancer-attributes --load-balancer-name $lb | jq '.LoadBalancerAttributes')
  if command -v gron >/dev/null; then
    echo "$output" | gron | while read -r line; do
      echo "elb:$lb attr:$line"
    done
  else
    echo "======= $lb ==========="
    echo "$output"
  fi
  echo
done
