#!/bin/bash

usage="$0 instance_ids"

if [[ $# -ne 1 ]]; then
  echo 'ERROR: Invalid usage'
  echo $usage
  exit 1
fi

instance_ids=$1

aws ec2 describe-instances --instance-ids $instance_ids | jq -r '.Reservations[].Instances[] | [.InstanceId, .BlockDeviceMappings[].Ebs.VolumeId] | join(":")'
