#!/bin/bash

content=$(cat)
output_file=$1

echo export AWS_ACCESS_KEY_ID="$(echo -e $content | jq -r '.Credentials.AccessKeyId')" | tee "$output_file"
echo export AWS_SECRET_ACCESS_KEY="$(echo -e $content | jq -r '.Credentials.SecretAccessKey')" | tee -a "$output_file"
echo export AWS_SESSION_TOKEN="$(echo -e $content | jq -r '.Credentials.SessionToken')" | tee -a "$output_file"
