#!/bin/bash

osascript -e 'Tell application "AnyBar" to set title to ""'
osascript -e 'Tell application "AnyBar_copy" to set title to ""'
osascript -e 'Tell application "AnyBar_copy_2" to set title to ""'

osascript -e 'Tell application "AnyBar" to set image name to "black"'
osascript -e 'Tell application "AnyBar_copy" to set image name to "black"'
osascript -e 'Tell application "AnyBar_copy_2" to set image name to "black"'
