#!/usr/bin/env python

import sys
import csv

lines = []

for line in sys.stdin:
  lines.append(line)

print '<table border="1">'

 # generate table contents

rownum = 0
for row in lines: # Read a single row from the CSV file
   # write header row. assumes first row in csv contains header
   if rownum == 0:
     print '<tr>'
     for column in row.split(','):
       print '<th>' + column + '</th>'
     print '</tr>'
   else:
      print '<tr>'    
      for column in row.split(','):
        print '<td>' + column + '</td>'
      print '</tr>'

   rownum += 1

print '</table>'
