#!/usr/bin/env python

import sys
import prettytable

table = None
for row in sys.stdin:
  if table is None:
    table = prettytable.PrettyTable(row.split(','))
  else:
    table.add_row(row.split(','))

print table
