#!/usr/bin/env python3

import os
import sys
import operator
import prettytable

table = None
add_sr_no = os.environ.get('TABLE_ADD_SR_NO', '0')
has_header = os.environ.get('TABLE_HAS_HEADER', '0')
align = os.environ.get('TABLE_ALIGN', 'l')
sortby_col = os.environ.get('SORT_BY')
sr_no = 1

for row in sys.stdin:
    row = row.strip()
    if row == '':
        continue
    if table is None:
        header_row = row.split(',')
        if has_header == '0':
            n_cols = len(header_row)
            if add_sr_no == '1':
                n_cols += 1
            header_row = ['h' + str(x) for x in range(n_cols)]
        else:
            if add_sr_no == '1':
                header_row = ['sr_no'] + header_row
        table = prettytable.PrettyTable(header_row)
    else:
        data_row = row.split(',', len(header_row) - 1)
        if add_sr_no == '1':
            data_row = [sr_no] + data_row
        table.add_row(data_row)
        sr_no += 1

if table:
    table.align = align
    if sortby_col:
        table.sortby = sortby_col
    print(table)
