#!/bin/bash

namespace="$1"
pod_prefix="$2"

pod_name=$(kubectl get pods --namespace $namespace | grep "^$pod_prefix" | head -1 | awk '{ print $1 }') 
echo "deleting pod: $pod_name" 
kubectl delete pod --namespace motocho $pod_name  --now
