#!/usr/bin/env python

import os
import sys
import boto

# dirty do-the-job script - no fancy arg parsing here - move on
if sys.argv[1] == 'help' or sys.argv[1] == '--help':
  print "upload-s3 file_path bucket"
  sys.exit(0)

def transfer_status(xferred, total):
  if xferred < 1024:
    print '%d bytes transferred out of %d bytes' % (xferred, total)
    return

  if 1024 < xferred < 1024 ** 2:
    xferred /= 1024.0
    total /= 1024.0
    print '%.2f KB transferred out of %.2f KB' % (xferred, total)
    return

  if 1024 ** 2 < xferred < 1024 ** 3:
    xferred /= 1024.0 ** 2
    total /= 1024.0 ** 2
    print '%.2f MB transferred out of %.2f MB' % (xferred, total)
    return

  if xferred >= 1024 ** 3:
    xferred /= 1024.0 ** 2
    total /= 1024.0 ** 2
    print '%.2f GB transferred out of %.2f GB' % (xferred, total)
    return

target_file = sys.argv[1]
target_bucket = sys.argv[2]

conn_s3 = boto.connect_s3()
bucket = conn_s3.get_bucket(target_bucket, validate=False)
k = boto.s3.key.Key(bucket)
k.key = os.path.basename(target_file)
k.set_contents_from_string(open(target_file, 'rb').read(), cb=transfer_status)
