#!/usr/bin/env python

import os
import sys
import boto

# dirty do-the-job script - no fancy arg parsing here - move on
if len(sys.argv) != 3 or sys.argv[1] == 'help' or sys.argv[1] == '--help':
  print "usage: upload-s3 file_path bucket"
  sys.exit(0)

def transfer_status(xferred, total):

  units = None
  if xferred <= 1024:
    units = 'bytes'
  elif 1024 < xferred < 1024 ** 2:
    xferred /= 1024.0
    total /= 1024.0
    units = 'KB'
  elif 1024 ** 2 < xferred < 1024 ** 3:
    xferred /= 1024.0 ** 2
    total /= 1024.0 ** 2
    units = 'MB'
  else:
    xferred /= 1024.0 ** 3
    total /= 1024.0 ** 3
    units = 'GB'

  print '%.2f %s transferred out of %.2f %s' % (xferred, units, total, units)

target_file = sys.argv[1]
target_bucket = sys.argv[2]

conn_s3 = boto.connect_s3()
bucket = conn_s3.get_bucket(target_bucket)
k = boto.s3.key.Key(bucket)
k.key = os.path.basename(target_file)
k.set_contents_from_string(open(target_file, 'rb').read(), cb=transfer_status)
